// Auto-generated by: npm run db:types
// Regenerate after migrations: supabase gen types typescript --local > src/types/database.ts

export type Database = {
  public: {
    Tables: {
      // Your tables will appear here after running db:types
    };
    Views: {};
    Functions: {};
  };
};
